#! /usr/bin/env php
<?php
date_default_timezone_set('UTC');
//use autoloader here in the real app
require '../src/Worker.php';
require '../src/Daemon.php';
require '../src/Master.php';
require 'QueueMaster.php';

$master = new QueueMaster('config.ini', 3600 * 24); //restart workers every 24 hours
$master->start();
